### ISSUE TITLE
Scale is not centered when zeros are included.

### ISSUE THREAD

**Issue by gerhardj** [nmalkin/plot-likert#23]
In this case, the middle option is on the right.

Example attached.
![Screenshot from 2021-11-23 20-42-07](https://user-images.githubusercontent.com/3588379/143092843-53f131cb-5674-41f2-bb8c-686117f66e94.png)

PS: is it possible to create custom names for the legend (even though the answers are in the format (1-7)?

**Comment by nmalkin** [comment]
Thank you for reporting this bug! I tracked down the issue and made a fix in commit 433a224.

Here's your sample code with the fix applied:

<img width="617"  src="https://user-images.githubusercontent.com/903179/143172566-62973996-0917-4e66-be41-bf8489ce32b6.png">

If you have other test cases you've been working with, can you verify that the fix works for them too? (You can `pip install git+https://github.com/nmalkin/plot-likert.git` to get the patched version.) Assuming it works, I'd like to cut a new release.

**Comment by nmalkin** [comment]
> PS: is it possible to create custom names for the legend (even though the answers are in the format (1-7)?

Yep, this should be possible [using the `legend` method on the axes object](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.legend.html?highlight=labels)

<img width="724" alt="2" src="https://user-images.githubusercontent.com/903179/143172595-5f165017-3c41-421f-8d33-b1a6cd6004d8.png">

Unfortunately, there's a little bit of funkiness because there are some invisible elements in the plot that get labeled if you just pass in the names directly. In this screenshot, I hid them by passing in special `'_'` values, but that produces the warnings you see above the graph. If you (or anyone reading) can figure out a way to do this more cleanly, please let me know; we can incorporate it into the user guide!

**Comment by nmalkin** [comment]
Released [0.3.7](https://github.com/nmalkin/plot-likert/releases/tag/v0.3.7). Thanks again for reporting this!

**Comment by gerhardj** [comment]
Many thanks for the quick fix and the help regarding the legend!
