### ISSUE TITLE
102% tick label

### ISSUE THREAD

**Issue by SapiensAnatis** [nmalkin/plot-likert#4]
Hi, just checked out this library and it seems pretty great so far. Only thing is that I'm having a weird issue where I have a 102% tick label because one of my series has an almost 100% response rate to one of the options.

![issue](https://user-images.githubusercontent.com/5047192/86872893-1f110e80-c0d5-11ea-99d4-115d76234101.png)

In my opinion, the ticks should only go to 100%, since I can't have 102% of respondents choosing a particular option.

I really appreciate this library, because I was dreading having to code a Likert plot myself, so if I have a spare minute or two I might see if I can submit a patch to fix this.

**Comment by nmalkin** [comment]
Thanks for this note and for the PR! I really appreciate you taking the time to not only report the issue but also write a fix for it.

I have a slight hesitation about the solution you propose in PR #5 (capping the highest label at 100%): it makes the tick intervals uneven: the last one will be different from all the others. This feels like it goes against standard practice for graphs. 

(Also it can just look awkward. Probably not in your example, since the interval is reduced from 17 points to 15, which isn't that noticeable, but maybe if the delta were larger: imagine if the next-to-last value were 95%, not 85%.)

However, I think we can actually expand on your approach for a more optimal solution. As long as we're going to special-case the percentage labels, we can take advantage of the fact that they're more predictable than regular labels. For example, we could declare that labels for percentages will always be 0%, 10%, 20%, …, 100%.

In reality, I think the solution will need to be a bit more nuanced than that, because this would leave a lot of extraneous whitespace, depending on the data distribution. Instead, the percentages should probably be capped at the maximum of the series.

I'm also wondering whether it's worth trying to make this work for non-percentage graphs, because the problem arguably affects them too: if I had a survey with 100 people, it might also look jarring (though maybe slightly less so) to have 102 as one of the labels.

Let me know what you think! I definitely want to fix this, and I'm looking forward to figuring out the best way how.

**Comment by alaskamike** [comment]
I think having the standard intervals (10,20,30 or even 20,40) is better
than the variable numbers.  17,34... is distracting - some people will try
to see if there is a significance to the number, but will essentially
ignore the round numbers.  Just my 2 cents.

Mike

**Comment by SapiensAnatis** [comment]
Yes, I agree with Mike. I think the best approach would be to re-do the way that the labels are calculated with a view to generating more sensible numbers. I will see if I can do that and will update my PR when I can.

**Comment by nmalkin** [comment]
I agree as well! :-) Thank you for your input and for planning to update your PR! 

I'll keep thinking, and if I have any more-concrete thoughts about what the label generation algorithm should look like, I'll post here. And once we have a good plan, I'm also very happy to help with the implementation.

**Comment by nmalkin** [comment]
I've given this a bit more thought, and I'm still not sure what the *best* solution is, but I came up with a couple of changes that, I think, make things overall better, and at least fix this specific issue.

First, in db79b64, I made a change so that, if any tick mark is higher than the total number of respondents, that *label* is hidden — but the tick mark itself remains (so as not to mess with spacing). So, in your original example, there would still be a tick mark at 102 (providing a visual cue of regular intervals), but the label would be gone (hopefully making it less confusing).

Next since our consensus above was that the auto-generated interval wasn't great, I added in 8b2a5dc a user-specified option for providing the size of the interval (similar to #5), though defaulting to the existing behavior, so that you don't *have* to specify anything if you don't care.

I recognize these changes are a bit more limited than what we've been discussing, so I'm happy to keep talking about other improvements. I do think this is an improvement over the current behavior that also fixes this issue!

**Comment by alaskamike** [comment]
When I run it with HIDE_EXCESSIVE_TICK_LABELS = True, it still prints a "%" where the value is hidden.

**Comment by nmalkin** [comment]
Argh, I clearly didn't test well enough. Fixed in d5161b9. Thanks, Mike!

**Comment by alaskamike** [comment]
Thanks, that's cleaner than the fix I was just getting ready to send!

**Comment by nmalkin** [comment]
Closing this now that #11 is merged. Thanks again everyone for your input, and let me know if you have further improvement suggestions!
